// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa sample": jwt Resource Client
//
// Command:
// $ goagen
// --design=github.com/tkc/goa-sandbox/design
// --out=$(GOPATH)/src/github.com/tkc/goa-sandbox
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// SecureJWTPath computes a request path to the secure action of jwt.
func SecureJWTPath() string {

	return fmt.Sprintf("/jwt")
}

// This action is secured with the jwt scheme
func (c *Client) SecureJWT(ctx context.Context, path string, fail *bool) (*http.Response, error) {
	req, err := c.NewSecureJWTRequest(ctx, path, fail)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSecureJWTRequest create the request corresponding to the secure action endpoint of the jwt resource.
func (c *Client) NewSecureJWTRequest(ctx context.Context, path string, fail *bool) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	if fail != nil {
		tmp9 := strconv.FormatBool(*fail)
		values.Set("fail", tmp9)
	}
	u.RawQuery = values.Encode()
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// SignInJWTPath computes a request path to the signIn action of jwt.
func SignInJWTPath() string {

	return fmt.Sprintf("/jwt/sign_in")
}

// Creates a valid JWT
func (c *Client) SignInJWT(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewSignInJWTRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewSignInJWTRequest create the request corresponding to the signIn action endpoint of the jwt resource.
func (c *Client) NewSignInJWTRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), nil)
	if err != nil {
		return nil, err
	}
	if c.SigninBasicAuthSigner != nil {
		if err := c.SigninBasicAuthSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}

// UnsecureJWTPath computes a request path to the unsecure action of jwt.
func UnsecureJWTPath() string {

	return fmt.Sprintf("/jwt/unsecure")
}

// This action does not require auth
func (c *Client) UnsecureJWT(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewUnsecureJWTRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUnsecureJWTRequest create the request corresponding to the unsecure action endpoint of the jwt resource.
func (c *Client) NewUnsecureJWTRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
