// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tkc/goa-sandbox/design
// --out=$(GOPATH)/src/github.com/tkc/goa-sandbox
// --version=v1.3.1

package client

import (
	"github.com/goadesign/goa"
	"net/http"
)

// DecodeErrorResponse decodes the ErrorResponse instance encoded in resp body.
func (c *Client) DecodeErrorResponse(resp *http.Response) (*goa.ErrorResponse, error) {
	var decoded goa.ErrorResponse
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// GoaExampleAccount media type (default view)
//
// Identifier: application/vnd.goa.example.account+json; view=default
type GoaExampleAccount struct {
	// Name of user
	Name *string `form:"name,omitempty" json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
	// Unique User Token
	Token *string `form:"token,omitempty" json:"token,omitempty" yaml:"token,omitempty" xml:"token,omitempty"`
	// Unique User ID
	UserID int `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// GoaExampleAccount media type (tiny view)
//
// Identifier: application/vnd.goa.example.account+json; view=tiny
type GoaExampleAccountTiny struct {
	// Unique User ID
	UserID int `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// DecodeGoaExampleAccount decodes the GoaExampleAccount instance encoded in resp body.
func (c *Client) DecodeGoaExampleAccount(resp *http.Response) (*GoaExampleAccount, error) {
	var decoded GoaExampleAccount
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// DecodeGoaExampleAccountTiny decodes the GoaExampleAccountTiny instance encoded in resp body.
func (c *Client) DecodeGoaExampleAccountTiny(resp *http.Response) (*GoaExampleAccountTiny, error) {
	var decoded GoaExampleAccountTiny
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}

// GoaExampleAccountCollection is the media type for an array of GoaExampleAccount (default view)
//
// Identifier: application/vnd.goa.example.account+json; type=collection; view=default
type GoaExampleAccountCollection []*GoaExampleAccount

// GoaExampleAccountCollection is the media type for an array of GoaExampleAccount (tiny view)
//
// Identifier: application/vnd.goa.example.account+json; type=collection; view=tiny
type GoaExampleAccountTinyCollection []*GoaExampleAccountTiny

// DecodeGoaExampleAccountCollection decodes the GoaExampleAccountCollection instance encoded in resp body.
func (c *Client) DecodeGoaExampleAccountCollection(resp *http.Response) (GoaExampleAccountCollection, error) {
	var decoded GoaExampleAccountCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}

// DecodeGoaExampleAccountTinyCollection decodes the GoaExampleAccountTinyCollection instance encoded in resp body.
func (c *Client) DecodeGoaExampleAccountTinyCollection(resp *http.Response) (GoaExampleAccountTinyCollection, error) {
	var decoded GoaExampleAccountTinyCollection
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return decoded, err
}
