// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa sample": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/tkc/goa-sandbox/design
// --out=$(GOPATH)/src/github.com/tkc/goa-sandbox
// --version=v1.3.1

package app
