// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "goa sample": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tkc/goa-sandbox/design
// --out=$(GOPATH)/src/github.com/tkc/goa-sandbox
// --version=v1.3.1

package app

// GoaExampleAccount media type (default view)
//
// Identifier: application/vnd.goa.example.account+json; view=default
type GoaExampleAccount struct {
	// Name of user
	Name *string `form:"name,omitempty" json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
	// Unique User Token
	Token *string `form:"token,omitempty" json:"token,omitempty" yaml:"token,omitempty" xml:"token,omitempty"`
	// Unique User ID
	UserID int `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// GoaExampleAccount media type (tiny view)
//
// Identifier: application/vnd.goa.example.account+json; view=tiny
type GoaExampleAccountTiny struct {
	// Unique User ID
	UserID int `form:"userId" json:"userId" yaml:"userId" xml:"userId"`
}

// GoaExampleAccountCollection is the media type for an array of GoaExampleAccount (default view)
//
// Identifier: application/vnd.goa.example.account+json; type=collection; view=default
type GoaExampleAccountCollection []*GoaExampleAccount

// GoaExampleAccountCollection is the media type for an array of GoaExampleAccount (tiny view)
//
// Identifier: application/vnd.goa.example.account+json; type=collection; view=tiny
type GoaExampleAccountTinyCollection []*GoaExampleAccountTiny
